### ISSUE TITLE
Not found handler raises internal error in production

### ISSUE THREAD

**Issue by lucastonelli** [BuilderIO/qwik-city-build#2]
Hello, everyone!

I've just started using Qwik with Qwik City by bootstraping the project using the [getting started guide](https://qwik.builder.io/docs/getting-started/). I was making changes locally and configuring things to deploy to an AWS Lambda function (using awsLambdaFastify) and modified the initial code very little. However, after having deployed the initial setup, I've noticed that when a page is not found when running in production environment the following error is being raised:

```json
{"statusCode":500,"error":"Internal Server Error","message":"Cannot read properties of undefined (reading 'Symbol(pino.msgPrefix)')"}
```
[Picture 1](https://user-images.githubusercontent.com/52139329/236587108-d5f3a21c-abab-4a71-9694-3557bcf19a26.png)

I've noticed that this happens because msgPrefix is lacking when `fastify.log.error` is called. This happens in the following piece of code:

```typescript
import { createQwikCity } from "@builder.io/qwik-city/middleware/node";
import fastifyStatic from "@fastify/static";
import qwikCityPlan from "@qwik-city-plan";
import type { FastifyPluginAsync } from "fastify";
import fastifyPlugin from "fastify-plugin";

import render from "../entry.ssr";

export interface FastifyQwikOptions {
  distDir: string;
  buildDir: string;
}

const { router, notFound } = createQwikCity({ render, qwikCityPlan });

const qwikPlugin: FastifyPluginAsync<FastifyQwikOptions> = async (
  fastify,
  options
) => {
  const { buildDir, distDir } = options;

  fastify.register(fastifyStatic, {
    root: buildDir,
    prefix: "/build",
    immutable: true,
    maxAge: "1y",
    decorateReply: false,
  });

  fastify.register(fastifyStatic, {
    root: distDir,
    redirect: false,
    decorateReply: false,
  });

  fastify.setNotFoundHandler(async (request, response) => {
    await router(request.raw, response.raw, fastify.log.error);
    await notFound(request.raw, response.raw, fastify.log.error);
  });
};

export default fastifyPlugin(qwikPlugin, { fastify: "4.x" });
```

When calling `await router(request.raw, response.raw, fastify.log.error);` instead of logging the error normally, that message is displayed.

I've tried adding a `msgPrefix` manually in the fastify logger configuration, but it didn't work.

Do you have any idea how to fix this? I'm still debugging to understand what might be hapenning.

**Comment by lucastonelli** [comment]
This is the log from CloudWatch:

```
2023-05-05T23:47:45.735Z	c2790762-b002-4e1b-bb2a-1e0438adbc73	ERROR	TypeError: Cannot read properties of undefined (reading 'Symbol(pino.msgPrefix)')
    at LOG (/var/task/node_modules/pino/lib/tools.js:68:22)
    at router (file:///var/task/server/entry.fastify.mjs:15:14872)
    at async Object.<anonymous> (file:///var/task/server/entry.fastify.mjs:15:15737)
```
